spring.application.name=config-service

#To make base path as http://localhost:9091/config/app/default
server.servlet.context-path=/config

#default config server port
server.port=8888

#Connecting to github
spring.cloud.config.server.git.uri=https://github.com/AbhishekUpadhyayVats/shopsphere-config.git
